# Example configuration for a NodeMCU v2 ESP8266 development board
substitutions:
  node_name: aqi-monitor-nodemcu
  i2c_pin_scl: D1
  i2c_pin_sda: D2
  bme280_i2c_address: "0x76"
  bme280_update_interval: 60s
  bme280_offset_temperature: "-1"
  mhz19b_pin_tx: D4
  mhz19b_pin_rx: D5
  mhz19b_update_interval: 60s
  mhz19b_calibration_interval: 30d
  sds011_pin_tx: D3
  sds011_pin_rx: D6
  sds011_update_interval: 5min
  led_pin_red: D7
  led_pin_green: D8
  led_pin_blue: TX

esp8266:
  board: nodemcuv2

dashboard_import:
  package_import_url: github://koenvervloesem/ESPHome-Air-Quality-Monitor/esphome-air-quality-monitor-esp8266.yaml@main

packages:
  base: !include common/base.yaml
  bme280: !include common/bme280.yaml
  mhz19b: !include common/mh-z19b.yaml
  sds011: !include common/sds011.yaml
  rgb: !include common/rgb_led/esp8266.yaml
  show_calibration: !include common/rgb_led/calibration.yaml
  show_aqi: !include common/rgb_led/aqi.yaml
  aqi: !include common/aqi.yaml
