# Base configuration for all air quality monitor nodes
#
# Used substitutions:
#
# - node_name: name of the device
# - node_platform: platform of the device
# - node_board: board of the device
#
# Used secrets:
#
# - wifi_ssid: SSID of the Wi-Fi network
# - wifi_password: password of the Wi-Fi network
# - wifi_ap_password: password of the fallback hotspot
# - api_password: API password
# - ota_password: OTA password

# These are the AQI threshold values and messages. Adapt to your needs.
substitutions:
  aqi_co2_max_good: "800"
  aqi_co2_max_acceptable: "1200"
  aqi_pm2_5_avg_24h_max_good: "12"
  aqi_pm2_5_avg_24h_max_acceptable: "25"  # WHO 2006
  aqi_pm10_avg_24h_max_good: "25"
  aqi_pm10_avg_24h_max_acceptable: "50"  # WHO 2006
  aqi_message_bad: "Bad"
  aqi_message_acceptable: "Acceptable"
  aqi_message_good: "Good"

esphome:
  name: ${node_name}
  platform: ${node_platform}
  board: ${node_board}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AP ${node_name}"
    password: !secret wifi_ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_password
