name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  publish-esp8266:
    name: Publish firmware for ESP8266
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: esphome-air-quality-monitor-esp8266.yaml
      name: ESPHome Air Quality Monitor for ESP8266
      manifest_filename: air-quality-monitor-esp8266-manifest.json
      clean: false
  publish-esp32:
    name: Publish firmware for ESP32
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: esphome-air-quality-monitor-esp32.yaml
      name: ESPHome Air Quality Monitor for ESP32
      manifest_filename: air-quality-monitor-esp32-manifest.json
      clean: false
  publish-t-display:
    name: Publish firmware for T-Display
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: esphome-air-quality-monitor-t-display.yaml
      name: ESPHome Air Quality Monitor for T-Display
      manifest_filename: air-quality-monitor-t-display-manifest.json
      clean: false
