name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  publish-esp32:
    name: Publish firmware for ESP32
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: esphome-air-quality-monitor-esp32.yaml
      name: ESPHome Air Quality Monitor for ESP32
      manifest_filename: air-quality-monitor-esp32-manifest.json
      clean: false